[package]
name = "chip8"
version = "0.1.0"
authors = ["William Guimont-Martin <wil9876543210@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
minifb = "0.16"
clap = "2"
libmath = "0.2.1"
